sudo: false

language: node_js

node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - alias hex="node ./bin/hex.js"
  - export PATH=$PATH:"./bin"

install:
  - yarn install --frozen-lockfile
  - yarn build
  - yarn link

after_success:
  - yarn send-coverage