environment:
  matrix:
    - node_version: "8"
    - node_version: "6"
    - node_version: "4"

branches:
  only:
  - master
  - /v[0-9]+(\.[0-9]+)*/

install:
  - ps: Install-Product node $env:node_version
  - choco install -i yarn
  - refreshenv
  - yarn install --frozen-lockfile
  - npm link

build_script:
  - yarn run build

test_script:
  - node --version
  - yarn --version
  - yarn run test

cache:
 - node_modules